project_name: fybe
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - main: ./main.go
    binary: fybe
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -w -s -X fybe.com/cli/fybe/cmd.version={{.Tag}}
archives:
  -
    name_template: "{{ .Binary }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
release:
  github:
    owner: fybecom
    name: fybe
  draft: false
  prerelease: auto
  header: |

  footer: |